### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by treakiandroid** [uberspot/2048-android#19]
Please add a change log, for example i would like to know what has changed between version 1.90 and 1.91 and between version 1.91And 1.95.

Thanks ang greatings. I am using fdroid:

2048 (Puzzle game) - https://f-droid.org/app/com.uberspot.a2048

**Comment by a-raccoon** [comment]
Could you include the gplay changelog in fdroid? Thanks :)

It took a quite a bit of digging and bumping around to figure out that Undo was the [major/only?] change introduced in v2.0.

**Comment by uberspot** [comment]
I had completely forgotten about this. Sorry about the delay.
Added in https://github.com/uberspot/2048-android/commit/92f16bd7176a6f39a77398e7d68db15b19207b88
