### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by akovia** [uberspot/2048-android#22]
Was thrilled when I found a free and open source version of this game, but it is just unplayable. It is incredibly laggy which boggles the mind as the graphics are rudimentary. My phone is a galaxy S6. Hope it can be improved.

**Comment by uberspot** [comment]
This is just a wrapper for https://github.com/uberspot/2048 
Which in turn could be greatly improved in terms of performance but the original devs have stopped contributing to the open source version and I have no time to work on js/css related stuff. 
Patches are accepted of course but I'm only able to bother with this android wrapper at the moment. :/
