### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by MishaTs** [uberspot/2048-android#23]
![screen shot 2015-08-03 at 12 43 03](https://cloud.githubusercontent.com/assets/12852413/9046141/8ac35b30-39dd-11e5-8221-dc01aea2735f.png)

**Comment by uberspot** [comment]
Did you install the F-Droid version or build it yourself? Did you do `git clone --recursive` ? It seems like the git submodule 2048 containing the site wasn't downloaded. Try to initialize the submodule before building.

**Comment by MishaTs** [comment]
I did git clone --recursive? Is there something else I need to do if i want to build? If i need the git submodule 2048, where can I get that?

**Comment by uberspot** [comment]
Try `git submodule update --init --recursive` inside the 2048-android directory.
This should create and populate the assets/2048 folder inside it. You should see some html/css/js files there. If they are there then maybe there's some problem during building. I use the latest android studio to build everything.

**Comment by MishaTs** [comment]
The git submodule update --init --recursive seemed to do the trick. Thanks!
