### ISSUE TITLE
Tapping on "undo" after "new game" produces three buttons

### ISSUE THREAD

**Issue by fxedel** [uberspot/2048-android#35]
If you tap on "undo", a screen with two buttons ("undo", "cancel") appears. And normally, if you tap on "new game", a screen with also two buttons ("ok", "cancel") appears.

But if you tap on "undo", don't dismiss the screen and tap additionally on "new game", there are three buttons: "undo", "ok" and "cancel". I'd expect the two buttons from one screen to be replaced by the two buttons from the other screen.

The three buttons' actions do work as intended.

**Comment by uberspot** [comment]
Fixed in https://github.com/uberspot/2048/pull/6
