### ISSUE TITLE
file:///android_asset/2048/index.html issue

### ISSUE THREAD

**Issue by TeejayParker** [uberspot/2048-android#36]
I downloaded the zip (yes, I extracted the zip file) from github to insert into android studio to check out / reverse engineer the code.

When I build to my phone, i get the error:  "file:///android_asset/2048/index.html is missing"
.
I guess I'm baffled as to why this is popping up, what am I missing?

I have included a screenshot of the build in android studio.

![2048screenshot](https://cloud.githubusercontent.com/assets/10538543/14973037/e2e9126c-10a8-11e6-94a7-2b21bdfa799e.PNG)

**Comment by TeejayParker** [comment]
I've tried the git submodule update --init --recursive inside the 2048-android-master directory, and for some reason the terminal in android studio doesn't recognize it.

**Comment by TeejayParker** [comment]
I have fixed my own issue.   /facepalms self, i can't believe I was overlooking this tiny issue.  lol

whoops on my part!  closing this issue.

**Comment by trevren11** [comment]
Could you explain how you fixed this issue? I am running into the same thing

**Comment by uberspot** [comment]
Check the readme. You have to clone the repo and initialize the submodules to get the html/js code.

**Comment by trevren11** [comment]
Ok, I think I have a different issue having to do with trying to do this on Windows Command line. Thanks for the quick response!

**Comment by thinkfun9261** [comment]
file:///android_asset/2048/index.html?lang=en
Facing issue with the built app.
What is the solution please??

**Comment by ildar** [comment]
It should be fixed somewhere near
https://github.com/uberspot/2048-android/commit/d3975d95c1b77a9f79fcf7bd132ffd8470c6642d
What commit are you building?
