### ISSUE TITLE
index.html missing

### ISSUE THREAD

**Issue by concordion2k** [uberspot/2048-android#40]
Hey,

the index.html file appears to be missing form the assets/2048 directory.

**Comment by LooneyZ** [comment]
Same thing, 2048 folder in assets is clear

**Comment by uberspot** [comment]
Follow the readme.md file for instructions. The git submodule wasn't pulled in your local repo. See closed issues on github for similar posts.

**Comment by gabriel-tandil** [comment]
one more piece of information: this didn't happen in the version you had previously installed but it happens now with the one you install from fdroid

**Comment by uberspot** [comment]
Yup, it's tracked in https://github.com/uberspot/2048-android/issues/74 
:)
