### ISSUE TITLE
Suspicion of copyright violation

### ISSUE THREAD

**Issue by Poussinou** [uberspot/2048-android#55]
Hi @uberspot 

I found [this app ](https://play.google.com/store/apps/details?id=com.appwala.a2048) and also [this one](https://play.google.com/store/apps/details?id=com.manisware.a2048) on Google Play Store. It seems that this apps are just the sames as your own app. This guys just took the source code, added some ads and put it on the Google Play Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove each false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT and this guy is violating it by distributing the app warning this is MIT licensed;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by uberspot** [comment]
Thanks for the notice, I filled a request on the site you linked. 👍 If I hear back from Google I'll let you know here. Till then I can close the issue. :)

**Comment by Poussinou** [comment]
Thanks.
I'll report here if I found any other one ;)

**Comment by atominvention** [comment]
Sorry to comment on an old issue, I was just interested in the project and looking at the license see what I am able to do with it.
For clarification, why are those guys violating copyright?
MIT license, in short, allows Commercial use, Modification, Distribution and Private use
People can add Ads in the app and publish on app store whatever they want, there is no "false app"

**Comment by sm4rk0** [comment]
They probably failed to do this:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

More info here: [The MIT License, Line by Line](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html).
