### ISSUE TITLE
Webpage not availbale

### ISSUE THREAD

**Issue by RonyMady** [uberspot/2048-android#62]
when i try to see the app on my phone before i do any change, i get an error 

"Webpage not available 
The webpage at
file:///android_asset/2048/index.html?lang=en could not be loaded because:
net::ERR_FILE_NOT_FOUND

**Comment by rafat69ahmed** [comment]
i am having the exact same problem

**Comment by gohsyi** [comment]
Having the same problem. Could anyone explain why?

**Comment by gohsyi** [comment]
I solved it by copying 2048-android/2048/ to 2048-android/app/src/main/assets/2048/

**Comment by uberspot** [comment]
https://github.com/uberspot/2048-android/issues/40  etc
