### ISSUE TITLE
F-Droid install not working

### ISSUE THREAD

**Issue by davebiffuk** [uberspot/2048-android#74]
I installed the app v2.1 from F-Droid and it's not working, I just get "The web page at file:///android_asset/2048/index.html?lang=en could not be loaded because:
net::ERR_FILE_NOT_FOUND"

I see others have reported this and the source fix is to do with git submodule, but that can't be right for the packaged app. Can it?

**Comment by davebiffuk** [comment]
I uninstalled the F-Droid 2.1 and installed 2.08 from Google Play, and that works fine.

**Comment by h1mal** [comment]
Getting the same error for 2.1. Android 5.1.1. Downgraded to 2.08 F-Droid by completely uninstalling 2.1 and doing a fresh 2.08 install - goodbye high score 😕

**Comment by CurtCumbersome** [comment]
Same here on official lineage 15.1 / SM-G900F

**Comment by ahangarha** [comment]
Same here. This is what i get:
```
The webpage at file:///android_asset/2048/index.html?lang=facould not be loaded because:

net::ERR_FILE_NOT_FOUND
```

**Comment by Karmalakas** [comment]
Same on Pixel 2 (Pie)

**Comment by shenzhui007** [comment]
Same on Oneplus 3T (Pie)

**Comment by themagicteeth** [comment]
The size in F-Droid is listed as only 38KiB vs 852KiB.

**Comment by uberspot** [comment]
I think it broke with https://github.com/uberspot/2048-android/commit/ec194a02997ca3b2a146a61f5d4a65de446ed790 @TacoTheDank any ideas? 
I'll try to have a look after work today/tomorrow otherwise.

**Comment by TacoTheDank** [comment]
@uberspot Yeah I think that's what the problem is. I'll go and change it back to assets, and then we should tag 2.1.1.

**Comment by a-raccoon** [comment]
In the mean time, who can issue a kill order to F-Droid.  The bad version is still being hosted today (12 days later).

**Comment by ahangarha** [comment]
> In the mean time, who can issue a kill order to F-Droid. The bad version is still being hosted today (12 days later).

How to do so?

**Comment by uberspot** [comment]
I just merged @TacoTheDank's fix and pushed a new tag and a new apk to play store. FDroid should also pick this up soon I guess (?)

**Comment by TacoTheDank** [comment]
@ahangarha @a-raccoon I don't think that's possible. The most we can do is just release the new version.

**Comment by a-raccoon** [comment]
There definitely needs to be a bug filed on https://gitlab.com/fdroid/fdroidclient for an "Emergency Take-down" report and removal system.  If not for critical errors, then for malicious apps.

**Comment by uberspot** [comment]
I saw the new release on fdroid and it seems to work on my side so I'll close this issue for now. If it happens again, do re-open it.

**Comment by TacoTheDank** [comment]
Yaaassss
