### ISSUE TITLE
error spanish?

### ISSUE THREAD

**Issue by gabriel-tandil** [uberspot/2048-android#76]
Error message:

Página web no disponible

Es posible que la página web file:///android_asset/2048/index.html?lang=es no esté disponible temporalmente o que se haya trasladado permanentemente a una dirección web nueva.

Sugerencias:

Asegúrese de tener una conexión de datos
Vuelva a cargar esta página web más tarde
Verifique la dirección ingresada

**Comment by uberspot** [comment]
Duplicate of https://github.com/uberspot/2048-android/issues/40
